### ISSUE TITLE
error reading json

### ISSUE THREAD

**Issue by markcc309** [oyurdakul/pesgm23#1]
Hello! Where do the `Alpha dis parameter` and `Mean prices` come from in `_from_json`? I can't find where these are generated when the scenarios are created?

**Comment by oyurdakul** [comment]
Hi @markcc309, thank you for the question. 

- Currently, the `alpha_dis` parameter in `_from_json` is defined (using the default value) but not used anywhere as discharging risk will be incorporated in the future. It is currently included so that when we do incorporate discharging risk, we will simply assign it to the `alpha_dis` parameter in `_from_json`. 

- `mean_prices` used in constructing the scenarios are formed in the `createScenarios` function provided [here](https://github.com/oyurdakul/pesgm23/blob/main/model/createScenarios.jl) based on the path to the CSV file containing the mean price values. The `mean_prices` vector in the `from_json` function, however, remained from a previous version of the code and it is not used anywhere. Thanks for pointing this out, it will be removed in the future.

Note that checking out [compute.jl](https://github.com/oyurdakul/pesgm23/blob/main/compute.jl) could provide a better overview as to how different functions interact.

**Comment by markcc309** [comment]
Thank you, @oyurdakul. I did read [compute.jl](https://github.com/oyurdakul/pesgm23/blob/main/compute.jl). I'm trying to implement this in Python/Pyomo, but having a little trouble getting my model to solve. In any case, this answered my question!
